version: 2
jobs:
  build:
    environment:
      PROJECT: "website-profile"
    working_directory: ~/app
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-builder-{{ checksum "package.json" }}
          - v1-builder-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-builder-{{ checksum "package.json" }}
      - run: npm run eslint
      - run: npm run build:server
      - run: npm run build:client
      - run: ls -al ./.nuxt/dist/server
      - run: rm -Rf node_modules
      - restore_cache:
          keys:
          - v1-production-{{ checksum "package.json" }}
          - v1-production-
      - run: npm i --only=production
      - save_cache:
          paths:
            - node_modules
          key: v1-production-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER --password $DOCKER_PASS container.touno.io
      - run: docker build -t container.touno.io/$PROJECT:latest .
      - run: PACKAGE_VERSION=v$(cat package.json | grep version | head -1 | sed 's/[version :\",]//g') && docker tag container.touno.io/$PROJECT:latest container.touno.io/$PROJECT:$PACKAGE_VERSION 
      - run: docker push container.touno.io/$PROJECT